---
services:
  web-service:
    image: umba/django-portfolio:latest
    build: ./web
    hostname: webapp
    command: "gunicorn -c config/gunicorn/dev.py"
    networks:
      - backend
  web-proxy:
    image: nginx
    volumes:
      - ./web/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/config/nginx/mime.types:/etc/nginx/mime.types:ro
      - ./web/src/static:/data/www/static
    ports:
      - "80:80"
    networks:
      - backend
networks:
  backend:
