FROM python:3.10.11-slim-bullseye

RUN apt-get update && \
    apt-get upgrade --yes

RUN useradd --create-home umba
USER umba
WORKDIR /home/umba

ENV VIRTUALENV=/home/umba/venv
RUN python3 -m venv $VIRTUALENV
ENV PATH="$VIRTUALENV/bin:$PATH"

COPY --chown=umba pyproject.toml constraints.txt ./
RUN python -m pip install --upgrade pip setuptools && \
    python -m pip install --no-cache-dir -c constraints.txt ".[dev]"

COPY --chown=umba src/ src/
# TODO: unit testing
# COPY --chown=umba test/ test/

RUN python -m pip install . -c constraints.txt && \
    # python -m pytest test/unit/ && \
    python -m flake8 src/ && \
    python -m isort src/ --check && \
    python -m black src/ --check --quiet && \
    # below is an example of how to disable false positive bugs
    # python -m pylint src/ --disable=C0114,C0116,R1705 && \
    python -m pylint src/ --disable=C0114,C0116,R1705 && \
    python -m bandit -r src/ --quiet

# TODO: update gunicorn config and move CMD to production dockerfile
# CMD ["gunicorn", "-c", "config/gunicorn/dev.py"]
