---
services:
  web-service:
    image: umba/django-portfolio:latest
    volumes:
      - ./web/config/gunicorn/dev.py:/home/umba/web/config/gunicorn/dev.py
    hostname: webapp
    command: "gunicorn -c web/config/gunicorn/dev.py"
    env_file: .env
    networks:
      - backend
  web-proxy:
    image: nginx
    volumes:
      - ./web/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/config/nginx/mime.types:/etc/nginx/mime.types:ro
      - ./web/src/static:/data/www/static
    ports:
      - "7890:80"
    networks:
      - backend
networks:
  backend:
