# Generated by Django 4.1.6 on 2023-04-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default='defaultgitlink', max_length=100),
            preserve_default=False,
        ),
    ]
